name       : mkdocs
version    : 1.4.2
release    : 1
source     :
    - https://github.com/mkdocs/mkdocs/archive/refs/tags/1.4.2.tar.gz : 71dbd91520a405cce9c1e194b98adeab369aed81e60debc9ca1ffe72f2132632
homepage   : https://www.mkdocs.org/
license    : BSD-2-Clause
component  : programming.tools
summary    : Project documentation with Markdown
description: |
    MkDocs is a fast, simple and downright gorgeous static site generator that's geared towards building project documentation. Documentation source files are written in Markdown, and configured with a single YAML configuration file. Start by reading the introductory tutorial, then check the User Guide for more information.
builddeps  :
    - pkgconfig(python3)
    - python-babel
    - python-build
    - python-hatchling
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-jinja
    - python-markdown
    - python-mergedeep
    - python-pyyaml-env-tag
    - python-watchdog
build      : |
    rm setup.py
    %python3_setup
install    : |
    %python3_install
